name: Wasm

on:
  pull_request:
  merge_group:
  push:
    branches:
      - master
      - kh-recursive-e2e

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-nargo:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu]

    steps:
      - name: Checkout Noir repo
        uses: actions/checkout@v4

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@1.66.0

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}
          cache-on-failure: true
          save-if: ${{ github.event_name != 'merge_group' }}

      - name: Build Nargo
        run: cargo build --package nargo_cli --release

      - name: Package artifacts
        run: |
          mkdir dist
          cp ./target/release/nargo ./dist/nargo
          7z a -ttar -so -an ./dist/* | 7z a -si ./nargo-x86_64-unknown-linux-gnu.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: nargo
          path: ./dist/*
          retention-days: 3

  build-wasm:
    runs-on: ubuntu-latest
    env:
      CACHED_PATH: /tmp/nix-cache

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - uses: nixbuild/nix-quick-install-action@v25
        with:
          nix_conf: |
            substituters = https://cache.nixos.org/ https://nix-community.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
            keep-outputs = true

      - name: Restore and cache Nix store - ${{ runner.os }}-flake-wasm
        uses: nix-community/cache-nix-action@v4
        with:
          # save a new cache every time ci file changes
          key: ${{ runner.os }}-flake-wasm-${{ hashFiles('flake.lock') }}
          restore-keys: |
            ${{ runner.os }}-flake-wasm
            gc-linux: true
            gc-max-store-size-linux: 1000000000
            
            # purge-caches: true
            # purge-key: ${{ runner.os }}-flake-wasm
            # purge-created: true
            # purge-created-max-age: 42

      - name: Build wasm package
        run: |
          nix build -L .#noir_wasm

      - name: Export cache from nix store
        if: ${{ steps.cache.outputs.cache-hit != 'true' && github.event_name != 'merge_group' }}
        run: |
          nix copy --to "file://${{ env.CACHED_PATH }}?compression=zstd&parallel-compression=true" .#noir-wasm-cargo-artifacts

      - uses: actions/cache/save@v3
        # Don't create cache entries for the merge queue.
        if: ${{ steps.cache.outputs.cache-hit != 'true' && github.event_name != 'merge_group' }}
        with:
          path: ${{ env.CACHED_PATH }}
          key: ${{ steps.cache.outputs.cache-primary-key }}

      - name: Dereference symlink
        run: echo "UPLOAD_PATH=$(readlink -f ./result/noir_wasm)" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: noir_wasm
          path: ${{ env.UPLOAD_PATH }}
          retention-days: 3

  test:
    needs: [build-wasm, build-nargo]
    name: Test noir_wasm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout noir-lang/noir
        uses: actions/checkout@v4

      - name: Download wasm package artifact
        uses: actions/download-artifact@v3
        with:
          name: noir_wasm
          path: ./compiler/wasm/downloaded

      - name: Download nargo binary
        uses: actions/download-artifact@v3
        with:
          name: nargo
          path: ./nargo

      - name: Compile test program with Nargo CLI
        working-directory: ./compiler/wasm/noir-script
        run: |
          nargo_binary=${{ github.workspace }}/nargo/nargo
          chmod +x $nargo_binary
          $nargo_binary compile

      - name: Install Yarn dependencies
        uses: ./.github/actions/setup

      - name: Install Playwright
        uses: ./.github/actions/install-playwright

      - name: Install dependencies
        run: |
          cp -r ./compiler/wasm/downloaded/nodejs ./compiler/wasm
          cp -r ./compiler/wasm/downloaded/web ./compiler/wasm
          yarn workspace @noir-lang/source-resolver build
          
      - name: Run node tests
        run: yarn workspace @noir-lang/noir_wasm test:node

      - name: Run browser tests
        run: yarn workspace @noir-lang/noir_wasm test:browser
